# Build settings
name: Fennec Creative
description: Chelsea Williams, Web Designer and Developer
author: Chelsea Williams
author_email: cwilliamsdigital@gmail.com
url: http://www.fenneccreative.com

seo:
  description: 'Personal website of Chelsea Williams, Web Designer and Developer'
  rel-author: 'https://plus.google.com/u/0/+FennecCreative/'
  rel-publisher: 'https://plus.google.com/u/0/+FennecCreative/'


markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested